### ISSUE TITLE
Run a program inside a docker container: segmentation fault occurs. 

### ISSUE THREAD

**Issue by Zapotecatl** [utelle/SQLite3MultipleCiphers#100]
Hi, I have successfully run my multiple cipher program in a virtual machine.

However, when I run the same program inside a docker container: a segmentation fault occurs. 

Specifically when I call `sqlite3mc_config` or `sqlite3_key`.

I had no problems installing multiple ciphers in the docker container build.

Please, any suggestions of what could be happening?

**Comment by utelle** [comment]
> I have successfully run my multiple cipher program in a virtual machine.
> However, when I run the same program inside a docker container: a segmentation fault occurs.

Your issue description is very vague, unfortunately. Which OS is running in your virtual machine? Which OS in your docker container? Did you build your application from scratch in each environment? Or did you just copy the executable?

> Specifically when I call `sqlite3mc_config` or `sqlite3_key`.

Well, a segmentation fault is a very generic error. Quite often the reason is that either a NULL pointer is referenced or the heap memory was somehow corrupted. The latter can happen, if your application erroneously overwrites memory locations.

At the moment there are no known issues in those 2 mentioned functions, `sqlite3mc_config` or `sqlite3_key`.

> I had no problems installing multiple ciphers in the docker container build.

Did you build SQLite3 Multiple Ciphers from scratch in the docker container? Or did you just install it in the docker container and built it in another environment? In the former case it is most likely that your own application is misbehaving, in the latter case there could be a mismatch of runtime libraries causing the problem.

> Please, any suggestions of what could be happening?

Hopefully my above comments can help you a bit to analyze the issue.

**Comment by Zapotecatl** [comment]
"_Your issue description is very vague, unfortunately._"

Yes completely, I was stuck and I did not pay attention to clarify ideas.

Docker was not the problem. I was careless in my Makefile I had `-lsqlite3` and `-lsqlite3mc`. I removed `-lsqlite3` and now everything works correctly.

"_Hopefully my above comments can help you a bit to analyze the issue._"

Always! I think, I am close to finish my project thanks to you!
