### ISSUE TITLE
CMakeLists.txt - add support for INSTALL command

### ISSUE THREAD

**Issue by jammerxd** [utelle/SQLite3MultipleCiphers#109]
CMakeLists needs to be updated to include support for the install command. The install command will copy all relevant sources into the bin, lib, include folders respectively.

**Comment by utelle** [comment]
Since I I have only limited experience with CMake, I will have to find out, how to do that. This will take some time.

On Linux like platforms you can use the autoconf/automake toolchain for which the install target is supported.

**Comment by jammerxd** [comment]
I'll try to make a PR that contains a prototype - it's actually really easy.

**Comment by utelle** [comment]
Great. TIA.

**Comment by taozuhong** [comment]
https://github.com/msys2/MINGW-packages/pull/18442

Maybe the PR could fix this build issue too.
@jammerxd @utelle

**Comment by jammerxd** [comment]
@taozuhong I don't think so since that uses make, not cmake.

**Comment by taozuhong** [comment]
The make script failed, so it must change the right method.

**Comment by utelle** [comment]
> [msys2/MINGW-packages#18442](https://github.com/msys2/MINGW-packages/pull/18442)
> 
> Maybe the PR could fix this build issue too. @jammerxd @utelle

It is unclear in which respect this PR should fix anything for CMake support in _SQLite3 Multiple Ciphers_. It's certainly nice for MinGW users if a pre-compiled package is availabe. However, the package is built using the autoconf/automake toolchain. This has nothing to do with CMake.

> @taozuhong I don't think so since that uses make, not cmake. make uses makefiles. CMake uses CMakeLists

The task here is to enhance `CMakeLists.txt` so that **installing** the compiled component is supported. We are not talking about providing pre-compiled packages.

> The make script failed, so it must change the right method.

Well, the CI runs of your PR all fail, because you use the undefined configure option `--disable-shell`. The autoconf/automake build files coming with _SQLite3 Multiple Ciphers_ currently do not support such an option, they always build the shell executable, but do not install it.

**Comment by taozuhong** [comment]
```text
 configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating sqlite3mc.pc
  config.status: executing depfiles commands
  config.status: executing libtool commands
  make: *** No rule to make target 'src/sqlite3shell.rc', needed by 'src/sqlite3shell.res_o'.  Stop.
  make: *** Waiting for unfinished jobs....
  ==> ERROR: A failure occurred in build().
      Aborting...
  ==> Removing installed dependencies...
  checking dependencies...
```
Update build script with your suggestion, failed again. @utelle

**Comment by utelle** [comment]
> ```
>  configure: creating ./config.status
>   config.status: creating Makefile
>   config.status: creating sqlite3mc.pc
>   config.status: executing depfiles commands
>   config.status: executing libtool commands
>   make: *** No rule to make target 'src/sqlite3shell.rc', needed by 'src/sqlite3shell.res_o'.  Stop.
>   make: *** Waiting for unfinished jobs....
>   ==> ERROR: A failure occurred in build().
>       Aborting...
>   ==> Removing installed dependencies...
>   checking dependencies...
> ```
> 
> Update build script with your suggestion, failed again. @utelle

It seems you have discovered a glitch in the autoconf/automake build files of _SQLite3 Multiple Ciphers_. At first glance I thought that the symbol `USE_MSW` is not defined, but actually it **_is_** defined in your case. The resource compiler is also found, as can be seen from the `configure` output

>>  checking for x86_64-w64-mingw32-windres... no
>>  checking for windres... windres

However, the resource file (used on Windows platforms) has a different name than given in `Makefile.am` - namely `sqlite3mc_shell.rc` instead of `sqlite3shell.rc`.

I will have to fix this. Personally, I never used the autoconf/automake build files under Windows. Therefore this glitch went undetected for such a long time.

If `USE_MSW` is defined (as is the case for you) It could be that it is also necessary to add `sqlite3mc.rc` to the source files of the library itself. And probably it is also necessary to remove the additional link libraries (`-ldl -lm`).

All the above needs to be tested and confirmed, before I can make a new release including the fixes.

**Comment by taozuhong** [comment]
I'll be happy to test the new release, thank you awfully for your great work.

**Comment by taozuhong** [comment]
I've tried the build process, it could produce the sqlite3shell.exe, yet the sqlite3mc library

```bash
../configure    ## produce sqlite3shell.exe
../configure --enable-static --enable-shared   ## produce sqlite3shell.exe, yet the library
```

**Comment by taozuhong** [comment]
I found them in the `.libs`, maybe the output directory should be `libs` or current directory:
![image](https://github.com/utelle/SQLite3MultipleCiphers/assets/13451009/dd542c59-d65c-4fb6-afe8-93bd0df4908c)

**Comment by utelle** [comment]
> I found them in the `.libs`, maybe the output directory should be `libs` or current directory:

No. This is how `libtool` works.

**Comment by taozuhong** [comment]
please release a new version, then I'll update and submit the mingw package, thanks.

**Comment by utelle** [comment]
> please release a new version, then I'll update and submit the mingw package, thanks.

I will try to make a new release within a couple of days.

**Comment by utelle** [comment]
[Version 1.7.1](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.7.1) is now available.

**Comment by utelle** [comment]
Commit https://github.com/utelle/SQLite3MultipleCiphers/commit/2c7a517cb48750d6530dd2af359824460ae1d4e2 adds CMake install support thanks to @Myroendan.
