### ISSUE TITLE
Will there be an installation package that supports Python django

### ISSUE THREAD

**Issue by Yeenhel** [utelle/SQLite3MultipleCiphers#112]
RT.

**Comment by utelle** [comment]
Since _SQLite3 Multiple Ciphers_ can easily replace the original _SQLite3_ library, because all additional API functions can be used via SQL functions or pragmas and URI paramaters, it should be quite straight forward to create such an installation package based on an existing SQLite package.

However, this is currently not on my to-do list and will therefore not happen in the near future. If someone else wants to undertake this task, I will give support, if necessary.

**Comment by Yeenhel** [comment]
谢谢您的回复。我是Python的初学者，也许可以自学
