### ISSUE TITLE
Compatibility with SQLeet

### ISSUE THREAD

**Issue by johnfound** [utelle/SQLite3MultipleCiphers#113]
I have tried to encrypt a database with SQLite3MC and then decrypt it with SQLeet, but failed.

Tried to read the docs on https://utelle.github.io/SQLite3MultipleCiphers/, but well, they are not very detailed in this very issue.

So, is it possible to configure SQLite3MC to be compatible with the SQLeet format? What options should be set and how?

**Comment by utelle** [comment]
> I have tried to encrypt a database with SQLite3MC and then decrypt it with SQLeet, but failed.

I assume you mean with _decrypt with SQLeet_ that you used the original [SQLeet library](https://github.com/resilar/sqleet) to decrypt the database file you encrypted with _SQLite3MC_.

That you failed is actually not surprising. By default _SQLite3MC_ uses the so-called _non-legacy mode_ to encrypt/decrypt database files unless told otherwise, but the original _SQLeet_ library operates in _legacy mode_. So, you have to tell _SQLite3MC_ that it should use _legacy mode_, too. 

> Tried to read the docs on https://utelle.github.io/SQLite3MultipleCiphers/, but well, they are not very detailed in this very issue.

The SQLite3MC documentation has a complete chapter about [legacy modes](https://utelle.github.io/SQLite3MultipleCiphers/docs/ciphers/cipher_legacy_mode/) which explains in detail the differences between _legacy modes_ and _non-legacy modes_.

> So, is it possible to configure SQLite3MC to be compatible with the SQLeet format? What options should be set and how?

Yes, of course it is possible to configure _SQLite3MC_ to be compatible with other _legacy_ encryption schemes like _SQLeet_. Simply use `PRAGMA legacy=1;` in _SQLite3MC_ to activate _legacy mode_.

**Comment by johnfound** [comment]
Thanks. The keyword here was "legacy", while I have searched for "compatibility" or like. Now everything is clear.
