### ISSUE TITLE
cipher_memory_security

### ISSUE THREAD

**Issue by dosint** [utelle/SQLite3MultipleCiphers#116]
Is it possible to add support for SQLCipher PRAGMA cipher_memory_security?

**Comment by utelle** [comment]
> Is it possible to add support for SQLCipher PRAGMA cipher_memory_security?

In principle, that would be possible. And it wouldn't be very hard to implement it. However, at the moment implementing this feature is not planned.

SQLCipher's implementation of that feature has 2 parts:

1. All memory allocated by SQLite will be "wiped out" with zeros on freeing a memory block
2. All memory allocated by SQLite will be locked in main memory, so that it will not be written to a system page file

Both actions cause significant performance degradation, so that the feature is turned off by default in SQLCipher.

(1) only prevents that another process can accidentally allocate memory that possibly contains sensitive information. If an intruder has already full access to your system, he/she can scan the main memory where SQLite holds its database cache - always unencrypted.

IMHO only with (2) a notable increase of security could be achieved, but it would be sort of pseudo security, because it can't be guaranteed that really **all** memory pages are locked.

Could you please describe in more detail under which circumstances you expect increased security by using such a feature?

One way to achieve higher security would be to encrypt the data values themselves, so that they would be encrypted even in memory cache until they are actually retrieved via a query. However, the drawback of this approach is that such data values can't be searched or sorted by SQL means. SQLCipher offers [Value Level Encryption](https://www.zetetic.net/sqlcipher/value-level-encryption) in its commercial product. And I consider to implement a similar feature in _SQLite3 Multiple Ciphers_ in a future release.

**Comment by utelle** [comment]
In the meantime I experimented a bit. As expected implementing a memory handler that clears memory allocations with zeros before freeing them is rather simple.

Calling `VirtualLock` / `VirtualUnlock` (resp `mlock` / `munlock`) (as is done in the SQLCipher implementation) would be easy, too. However, the usefulness of this approach is really, really questionable. Neither `VirtualLock` / `VirtualUnlock` nor `mlock` / `munlock` use a reference count of locked memory regions. The granularity of locking is a memory page, that is, if SQLite makes several small memory allocations from a single memory page, the first unlock operation for one of the allocations will unlock the page, even though there are still not yet freed allocations. Additionally, _suspending to disk_ will not be prevented by using memory locks. That is, the _"protection"_ is full of holes like Swiss cheese.

I don't want to give users the illusion of security that actually doesn't exist. Therefore I will not implement such memory locking. If you feel clearing memory allocations that are about to be freed, would be a gain in security, please let me know.

**Comment by dosint** [comment]
I see, thank you for comments

**Comment by dosint** [comment]
Can this feature be added like this:

` url = "jdbc:sqlite:" + path + "?cipher=sqlcipher" + "?memory_security=1";`

**Comment by utelle** [comment]
> Is this the correct way to enable memory_security?
> 
> ` url = "jdbc:sqlite:" + path + "?cipher=sqlcipher" + "?memory_security=1";`

No. 

1. The syntax is wrong; see [URI filenames in SQLite](https://www.sqlite.org/uri.html) for how to specify parameters in a URI filename.
2. The parameter `memory_security` can currently be set via `pragma` command only.

Additionally, the pragma will have no effect, unless the library was compiled with the preprocessor symbol `SQLITE3MC_SECURE_MEMORY=1` defined. The feature is disabled by default.

> If yes, what should we add to enable USE_RANDOM_FILL_MEMORY?

This is a compile time option only. If you want that memory is filled with random data instead of zero bytes then you'll have to specify the symbol `SQLITE3MC_ENABLE_RANDOM_FILL_MEMORY=1` at compile time.

I will close the issue, because the usefulness of this "feature" is questionable anyway and I don't intend to invest time into further development of it, unless strong justification is provided.

If this feature is critical for your application, you may change my mind by making a reasonable donation (see "Sponsor this project" on the [main repo page](https://github.com/utelle/SQLite3MultipleCiphers)).
