### ISSUE TITLE
Feature Request: Multiplex

### ISSUE THREAD

**Issue by titanism** [utelle/SQLite3MultipleCiphers#121]
Is it possible for multiplex extension to be added? <<https://www.sqlite.org/src/doc/trunk/src/test_multiplex.c>>

Or how might one use this with <https://github.com/m4heshd/better-sqlite3-multiple-ciphers>?  Assuming a custom build would be required with added extensions.

**Comment by utelle** [comment]
> Is it possible for multiplex extension to be added? <https://www.sqlite.org/src/doc/trunk/src/test_multiplex.c>

Normal SQLite extensions are usually _loadable extensions_ adding functionality that can be used from SQL via so-called user-defined functions. This is not the case for the _multiplex extension_. This extension is not a loadable extension but a SQLite VFS shim. It adds a special entry point for initializing the extension and requires that certain file-control operations can be executed.

That is, you can't simply add this extension without further modifications. Therefore I don't plan to add this extension.

Using this extension in combination with _SQLite3 Multiple Ciphers_ is not trivial. _SQLite3 Multiple Ciphers_ is also a VFS shim. Although it is possible to use nested VFS shims, you need to know what you are doing. For example, the _multiplex_ shim would have to sit between the _SQLite3 Multiple Ciphers_ shim and the real VFS to be operational. Otherwise you will most likely get corrupted database files.

> Or how might one use this with https://github.com/m4heshd/better-sqlite3-multiple-ciphers? Assuming a custom build would be required with added extensions.

I don't know any details about [better-sqlite3-multiple-ciphers](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/) and personally I never used it so far, but you would definitely need to do a custom build and to adjust/extend the _better-sqlite3-multiple-ciphers_ API.
