### ISSUE TITLE
CMake: APIs not exported when building shared library

### ISSUE THREAD

**Issue by Myroendan** [utelle/SQLite3MultipleCiphers#123]
Hi!
When building with CMake, the shared library is missing some important API-s (sqlite3_key for example). I have checked the CMakeLists.txt, there is a variable which is defined, but never used:
set(SQLITE3MC_DLLRES_SRCS
  src/sqlite3mc.def
  src/sqlite3mc.rc
)
The .def is needed to export the apis when building as a shared lib.
I added this to the sources, but then I got 54 undefined reference link errors. 
These 54 functions are not present in the static library, I'm not sure why they are listed. If I remove them from the def file, the shared lib builds fine and contains the necessary apis.

**Comment by utelle** [comment]
> When building with CMake,

Unfortunately, I myself have only very limited experience with CMake. CMake support was contributed by another user.

> the shared library is missing some important API-s (sqlite3_key for example). I have checked the CMakeLists.txt, there is a variable which is defined, but never used: set(SQLITE3MC_DLLRES_SRCS src/sqlite3mc.def src/sqlite3mc.rc )

In case of a shared library build these files should be added, but obviously the CMake instruction to do that is missing.

> The .def is needed to export the apis when building as a shared lib. I added this to the sources, but then I got 54 undefined reference link errors.

As you observed the .def file is not really suited to solve the problem. The reason is that the .def file reflects the extension selection used by the pre-generated build files coming with SQLite3 Multiple Ciphers. Depending on the actual option selection in CMake the .def file will contain entries for functions that are not enabled.

> These 54 functions are not present in the static library, I'm not sure why they are listed.

They are listed, because they are compiled in with the pre-generated build files.

> If I remove them from the def file, the shared lib builds fine and contains the necessary apis.

A better option to enable the API actually compiled in will be to define the preprocessor symbol `SQLITE_API=__declspec(dllexport)` if a shared library/DLL is built.

I will try to adjust the CMake file, but this may take a while.

**Comment by Myroendan** [comment]
Defining the preprocessor symbol worked, the .def file is not needed with this method. The .rc file should still be added to the sources if I'm correct. I will create a pull request with the changes.

**Comment by utelle** [comment]
> Defining the preprocessor symbol worked, the .def file is not needed with this method.

Correct.

> The .rc file should still be added to the sources if I'm correct.

Yes, this will add version information to the resulting DLL.

> I will create a pull request with the changes.

TIA.

**Comment by utelle** [comment]
PR https://github.com/utelle/SQLite3MultipleCiphers/pull/125 fixing this issue was merged. Closing...
