### ISSUE TITLE
CMake and make script won't export user authentication functions

### ISSUE THREAD

**Issue by taozuhong** [utelle/SQLite3MultipleCiphers#133]
The library built by autotools script: missing most of functions
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-sqlite3mc/PKGBUILD
![image](https://github.com/utelle/SQLite3MultipleCiphers/assets/13451009/055b6446-1854-4fee-954b-ffe8aa511f69)

The library built by CMake script: missing user authentication functions only
![image](https://github.com/utelle/SQLite3MultipleCiphers/assets/13451009/e19ddd0c-c73d-47a0-a2e1-3ee989c20111)

Anything missing by me?

**Comment by utelle** [comment]
> The library built by autotools script: missing most of functions https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-sqlite3mc/PKGBUILD

Well, the autoconf/automake build files coming with sqlite3mc were originally not meant to be used on Windows platforms (MSYS). However, I agree that it would be nice to have them working there as well.

> The library built by CMake script: missing user authentication functions only

The CMake script was adjusted recently to define the preprocessor symbol `SQLITE_API=__declspec(dllexport)` in case a shared/DLL library is built. The file `Makefile.am` needs to be adjusted to use the same approach under Windows.

As you observed this works for all API functions ... except the ones of the user authentication. The reason is that the functions of the user authentication API are not decorated with the symbol `SQLITE_API`.

To be frank I'm extremely sorry to have added the user authentication extension at all. It keeps causing issues all the time. This extension is provided by the SQLite core developer team, but it is not maintained well. There are flaws in the implementation, but bug reports are ignored.

Actually, the user authentication is not very useful, because it prevents unauthorized access only, if it was compiled into the SQLite library. If you access a database file, that was created with a user authentication enabled SQLite library, with a SQLite library that does not contain this extension, you can freely access all data in the database.

**Comment by taozuhong** [comment]
Found that the user authentication functions missing prefix `SQLITE_API`, add it will be exported.

**Comment by utelle** [comment]
Commit https://github.com/utelle/SQLite3MultipleCiphers/commit/85be37ebbe9b5b2c81e6dd8fad09ae4684fad192 should fix the issue with missing exported API functions.

The preprocessor symbol `SQLITE_API` is now used to flag public API functions.
