### ISSUE TITLE
 Some error occurred while compiling sqlite3mc. c using Bcc32c

### ISSUE THREAD

**Issue by topmin** [utelle/SQLite3MultipleCiphers#141]
Some error occurred while compiling sqlite3mc. c using Bcc32c:
[bcc32c Error] sqlite3mc. c (273457):'_builtin_ia32aeskigenassist128 'needs target feature aes
[bcc32c Error] sqlite3mc. c (273457): always_inline function 'mm_setr_epi32' requires target feature 'mmx', but would be inline into function 'aesGenKeyEncryptInternal' that is compiled without support for 'mmx'

**Comment by utelle** [comment]
> Some error occurred while compiling sqlite3mc. c using Bcc32c: [bcc32c Error] sqlite3mc. c (273457):'_builtin_ia32aeskigenassist128 'needs target feature aes [bcc32c Error] sqlite3mc. c (273457): always_inline function 'mm_setr_epi32' requires target feature 'mmx', but would be inline into function 'aesGenKeyEncryptInternal' that is compiled without support for 'mmx'

The compile time errors have to do with the compilation of the AES hardware support code. The error messages tell you exactly what is missing:

- target feature `aes`
- target feature `mmx`

That is, you will have to specify additional compiler options to enable those target features. For the `gcc` compiler the options are `-maes -msse4.2`, but I don't know what the corresponding options for `bcc32c` would be.

Alternatively, you can avoid the compile errors by specifying the preprocessor symbol `SQLITE3MC_OMIT_AES_HARDWARE_SUPPORT`. However, this will then disable native AES hardware support.

**Comment by topmin** [comment]
I couldn't find the AES and MMX options for bcc32c, so I used SQLITE3MC-OMIT-AES-HARDWARESUPPORT to compile it, but there was some error when linking:
[ilink32 Error] Error: Unresolved external '_rand_s' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ
[ilink32 Error] Error: Unresolved external '_ASCON_P6ROUNDS' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ
[ilink32 Error] Error: Unresolved external '_ascon_absorb' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ
[ilink32 Error] Error: Unresolved external '_ASCON_P12ROUNDS' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ

**Comment by utelle** [comment]
In the meantime I installed the C++Builder community edition for testing. However, I've never seen such a crippled C++ development environment before. Depending on the selected build (debug vs release, Win32 vs Win64) I got various different error messages.

> I couldn't find the AES and MMX options for bcc32c, so I used SQLITE3MC-OMIT-AES-HARDWARESUPPORT to compile it,

I haven't found corresponding options either, but selecting the `clang` compiler instead of the `classic` compiler allowed me to compile the AES hardware support code without issues.

> but there was some error when linking: [ilink32 Error] Error: Unresolved external '_rand_s' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ

Well, C++Builder obviously doesn't implement the `rand_s` function. To overcome this obstacle you have to define the preprocessor symbol `SQLITE3MC_USE_RAND_S=0`.

> [ilink32 Error] Error: Unresolved external '_ASCON_P6ROUNDS' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ [ilink32 Error] Error: Unresolved external '_ascon_absorb' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ [ilink32 Error] Error: Unresolved external '_ASCON_P12ROUNDS' referenced from D:\PROJECTS\SQLITE3MC\WIN32\RELEASE\SQLITE3MC.OBJ

For whatever reason the C++Builder compiler refuses to compile the code marked as `inline`. As mentioned above I used the compiler in `clang` mode, **but** the compiler does **not** define the preprocessor symbol `__CLANG__`. If I add the preprocessor symbol `__CLANG__` manually, the code compiles without errors.

At first I had tried to build the `Win32` variant, but the linker complained about an unresolved reference. I found out that C++Builder provides it only for `Win64` (no idea why not for `Win32`). So I switched to `Win64`.

Nevertheless the linker now complained about not being able to load the system link library `advapi32.lib`. The reason is that C++Builder does not provide it for all build configurations, and - what's worse - does not name it consistently: in some build configurations it is named `advapi32.lib`, but in some `advapi32.a`.

After these "experiences" I come to the conclusion that I will not add official support for C++Builder - it is simply too cumbersome to overcome the deficiencies of that compiler.

You may be able to get it to work somehow with the configuration you need. However, I would recommend to use a different compiler (like _Visual C++_ or _MinGW-W64_).

**Comment by topmin** [comment]
Add the following three lines at the beginning of the sqlite3mc. c file, and compile them successfully.

> #Define _ CLANG__
> #Define SQLITE3MC-USE-RAND_S 0
> #Define SQLITE3MC-OMIT-AES-HARDWARESUPPORT

Thank you for your patient guidance and for creating the great project SQLite3MultipleCiphers.

**Comment by utelle** [comment]
> Add the following three lines at the beginning of the sqlite3mc. c file, and compile them successfully.
> 
> ```C
> #define __CLANG__
> #define SQLITE3MC_USE_RAND_S 0
> #define SQLITE3MC_OMIT_AES_HARDWARE_SUPPORT
> ```

Good to hear that defining those preprocessor symbols allowed you to successfully compile with the `bcc32c` compiler.

Specifying the symbol `SQLITE3MC_OMIT_AES_HARDWARE_SUPPORT` should not be necessary - but it may depend on the actual version of `bcc32c`.

Please understand that I will not add these defines to the source code - at least not unconditionally.

> Thank you for your patient guidance and for creating the great project SQLite3MultipleCiphers.

You are welcome. I'll close the issue now as _resolved_.
