### ISSUE TITLE
Link error when ‘#define HAVE_CIPHER_CHACHA20 0’

### ISSUE THREAD

**Issue by topmin** [utelle/SQLite3MultipleCiphers#146]
#define SQLITE3MC_USE_RAND_S 0
#define HAVE_CIPHER_AES_128_CBC 0
#define HAVE_CIPHER_AES_256_CBC 0
#define HAVE_CIPHER_CHACHA20 0
#define HAVE_CIPHER_SQLCIPHER 0
#define HAVE_CIPHER_RC4 0
#define HAVE_CIPHER_ASCON128 1
#define CODEC_TYPE CODEC_TYPE_ASCON128

Unresolved external '_chacha20_rng' referenced from SQLITE3MC.OBJ
Unresolved external '_STORE32_BE' referenced from SQLITE3MC.OBJ

**Comment by utelle** [comment]
> #define SQLITE3MC_USE_RAND_S 0
> #define HAVE_CIPHER_AES_128_CBC 0
> #define HAVE_CIPHER_AES_256_CBC 0
> #define HAVE_CIPHER_CHACHA20 0
> #define HAVE_CIPHER_SQLCIPHER 0
> #define HAVE_CIPHER_RC4 0
> #define HAVE_CIPHER_ASCON128 1
> #define CODEC_TYPE CODEC_TYPE_ASCON128
> 
> Unresolved external '_chacha20_rng' referenced from SQLITE3MC.OBJ Unresolved external '_STORE32_BE' referenced from SQLITE3MC.OBJ

The cipher scheme _Ascon128_ uses parts of the code of the _ChaCha20_ implementation, namely the random number generator. Therefore you get unresolved external references, if you disable the cipher _ChaCha20_.

I will adjust the code, so that the _ChaCha20_ implementation will be included, even if the cipher _ChaCha20_ was disabled.

For the time being you can enable the _ChaCha20_ cipher as a work around.

**Comment by utelle** [comment]
Commit 26c5c5bd3bd6fc8fe24caf647809891865e6e1b0 fixes the issue.

**Comment by topmin** [comment]
Thank you.
