### ISSUE TITLE
Question about versions

### ISSUE THREAD

**Issue by Willena** [utelle/SQLite3MultipleCiphers#15]
Hi, 

Just a simple question, wouldn't it be confusing for developers to have a different version number between SQLite3MC and the official SQLite3 library ? 
For example, how do I know that 1.0.0 correspond effectively to version 3.33.0 of SQLite3 ?

I perfectly understand why SQLite3MC has a different version number, due to the fact some internal modification have been made to SQLite3. 

I don't really know what the best option is, maybe double tag each release (one tag for SQLite3MC and one to keep a reference to SQLite3) ?

Applied to the current release, we would have:
tag 1 (SQLite3MC): 1.0.0
tag 2 (SQLite3) : SQLite3 - 3.33.0

Any suggestions or thoughts ?

**Comment by utelle** [comment]
> Just a simple question, wouldn't it be confusing for developers to have a different version number between SQLite3MC and the official SQLite3 library ?

Well, it is indeed a bit annoying to have to deal with different version numbers. However, the situation is no different for other SQLite-based components like [System.Data.Sqlite](https://system.data.sqlite.org) or [SQLCipher](https://www.zetetic.net/sqlcipher/). They use their own version numbers. For my own component [wxSQLite3](https://github.com/utelle/wxsqlite3) the situation now is even worse, now that it is based on [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers) - I have to deal with **_3_** different version numbers.

> For example, how do I know that 1.0.0 correspond effectively to version 3.33.0 of SQLite3 ?

You don't - unless you look into the release description which will tell you on which version of SQLite3 the release is based.

> I perfectly understand why SQLite3MC has a different version number, due to the fact some internal modification have been made to SQLite3.

That's exactly the problem: it may be necessary to make adjustments which are not in sync with the releases of the underlying SQLite3 library.

> I don't really know what the best option is, maybe double tag each release (one tag for SQLite3MC and one to keep a reference to SQLite3) ?

I don't think that using multiple tags on the same commit is a good idea. IMHO it simply adds to the confusion, because some git tools can't handle multiple tags on the same commit properly.

> Applied to the current release, we would have:
> tag 1 (SQLite3MC): 1.0.0
> tag 2 (SQLite3) : SQLite3 - 3.33.0
> 
> Any suggestions or thoughts ?

An alternative could be to use extended tags. For example, instead of using simply `v1.0.0` the SQLite3 version could be appended to the tag in the future: `v1.0.0-3.33.0` or `v1.0.0-SQLite3.33.0` or `v1.0.0-sqlite-3.33.0` or any other form which seems appropriate. I'm open to suggestions.

However, doing so would impose another question: if a new version of SQLite3 is released, which does not require any changes to SQLite3MC except for patching the original SQLite3 code, should the version number of SQLite3MC be changed or not? That is, would we have `v1.0.0-3.33.1` or `v1.0.1-3.33.1`? At the moment I would simply use `v1.0.1` in such a case.

I'm not convinced that adding the SQLite3 version number to the release tags is such a good idea, after all.

**Comment by Willena** [comment]
> An alternative could be to use extended tags. For example, instead of using simply `v1.0.0` the SQLite3 version could be appended to the tag in the future: `v1.0.0-3.33.0` or `v1.0.0-SQLite3.33.0` or `v1.0.0-sqlite-3.33.0` or any other form which seems appropriate. I'm open to suggestions.
> 
> However, doing so would impose another question: if a new version of SQLite3 is released, which does not require any changes to SQLite3MC except for patching the original SQLite3 code, should the version number of SQLite3MC be changed or not? That is, would we have `v1.0.0-3.33.1` or `v1.0.1-3.33.1`? At the moment I would simply use `v1.0.1` in such a case.
> 

Using extended tags are good for me. They are readable, and they contain all the information needed . As an example, imagine we have a bug inside the SQLite3 3.33.0, with such naming on tags, I can very quickly see witch SQliteMC version correspond to SQLite 3.31.0 (I know this version does not exist but it is for the example). Something like  `v1.0.0-SQLite3.33.0` or `v1.0.0-sqlite-3.33.0` would be better I think.

**Comment by utelle** [comment]
Personally, I'm not so fond of adding the SQLite version number to the tags.

I see 3 other options:

1) The SQLite version number could be added to the Github release title.
Example: The current release title `SQLite3 Multiple Ciphers 1.0.0` would become `SQLite3 Multiple Ciphers 1.0.0 (based on SQLite 3.33.0)`
The problem with this approach would be that the release title (and hence the SQLite version number) is not visible within the git repository itself.
2) _Annotated_ tags could be used instead of _lightweight_ tags - and the SQLite version number would be included in the annotation message.
This approach would address the problem of option (1), but would most likely not show the annotation message in the Github release.
3) Combining option (1) and (2).

**Comment by Willena** [comment]
I saw that you already started to use (1) in the recent release. Assets to the release also get this naming and it is perfect for the GitHub side of things. 
I would combine (1) and (2). So that the git command line interface could be used to filter tags without the need to go back the release page.

**Comment by utelle** [comment]
Unfortunately, the GitHub web interface for preparing a release doesn't offer the option to create an annotated release tag. That is, tagging has to be done separately from the git command line, before preparing a release. That is a bit inconvenient, but I'll try to do it for the next release.

**Comment by utelle** [comment]
@Willena 
Before making the [latest release](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.1.0) I created an annotated tag (_v1.1.0_ with the annotation _"based on SQLite 3.34.0"_). Please check, whether this helps you to identify the underlying SQLite version. If yes, I'll try to remember to do it for coming releases, too. If no, I can spare the extra effort.

**Comment by Willena** [comment]
Thank you very much !  Combined with the assets names this solution fits my needs !
