### ISSUE TITLE
Cipher configuration pragmas return values as strings, not int

### ISSUE THREAD

**Issue by rogerbinns** [utelle/SQLite3MultipleCiphers#161]
When doing cipher configuration pragmas I am checking the value returned against the value I supplied to verify the pragma was understood, the value was in range, and the value was applied.

Annoyingly the value returned from the pragma is always a string, and not an integer for integer values.  This is unexpected.

All the rest of the SQLite pragmas return integers for integer values.  Here is a short example:
````
import apsw

con = apsw.Connection("")
print(f"{con.pragma("kdf_iter")=}")
print(f"{con.pragma("page_size")=}")
````

Produces

````
con.pragma("kdf_iter")='64007'
con.pragma("page_size")=4096
````

Where you can see `kdf_iter` is coming back as a string, while `page_size` is an integer.

**Comment by utelle** [comment]
> When doing cipher configuration pragmas I am checking the value returned against the value I supplied to verify the pragma was understood, the value was in range, and the value was applied.

In principle, a good idea, of course.

> Annoyingly the value returned from the pragma is always a string, and not an integer for integer values. This is unexpected.

Yes, I agree, it would be nice to return the result with an appropriate type instead of always returning a string.

Unfortunately I can't do much about it. The pragma handling is done via the official SQLite mechanism. SQLite's pragma handler calls the function `sqlite3_file_control` with the id `SQLITE_FCNTL_PRAGMA`. If the VFS can handle the given pragma, the function returns `SQLITE_OK`. Otherwise the normal pragma handling continues.

A comment in SQLite's source code ( `test_multiplex.c`) reads:

>> The handler for an SQLITE_FCNTL_PRAGMA file control can optionally make the first element of the char** argument point to a string obtained from sqlite3_mprintf() or the equivalent and that string will become the result of the pragma or the error message if the pragma fails.

That is, only a single string value can be returned from one's own pragma handler - either a value or an error message.

You could argue that I already apply several patches to SQLite, so that probably one more wouldn't matter much.

**Comment by rogerbinns** [comment]
The [doc](https://utelle.github.io/SQLite3MultipleCiphers/docs/configuration/config_sql_pragmas/#usage-of-pragma-statements) doesn't mention checking the return of pragmas, nor that they are strings.

I suggest fixing this issue by updating the doc advising that the string of the value in effect is returned.  That way you know the pragma was understood and within range.  pragma key/hexkey will need note that it returns "ok".

**Comment by rogerbinns** [comment]
> That is, only a single string value can be returned from one's own pragma handler

That turns out to be the case if you [write a pragma handler](https://rogerbinns.github.io/apsw/vfs.html#apsw.VFSFcntlPragma.result) in APSW too!

The `apply_encryption` function in apsw-sqlite3mc checks against the string value, so it does the right thing in the circumstances.  Closing.
