### ISSUE TITLE
thread 'main' panicked during install

### ISSUE THREAD

**Issue by chrishawkins2013** [utelle/SQLite3MultipleCiphers#163]
I am getting the following error when attempting to pip install libsql-experiemental. It seems to be traced back to this particular portion of the package. main part of the error is below. I have been able to find anything helpful on this. Trying to install on a Mac.   

thread 'main' panicked at /Users/UserName/.cargo/git/checkouts/libsql-e519d6234c1a233a/5a806fe/libsql-ffi/build.rs:358:33:
        called `Result::unwrap()` on an `Err` value: Os { code: 86, kind: Uncategorized, message: "Bad CPU type in executable" }

**Comment by rogerbinns** [comment]
> Bad CPU type in executable

That error code from MacOS means it has encountered an executable that doesn't match.  For example it will happen with a 32 bit executable since MacOS only supports 64 bit, or encountering an ARM binary on x64.  You'll need to figure out what was being run.

You should take this up with https://github.com/tursodatabase/libsql-experimental-python

They have two open issues with pip install on MacOS - [#55](https://github.com/tursodatabase/libsql-experimental-python/issues/55) and [#58](https://github.com/tursodatabase/libsql-experimental-python/issues/58)
