### ISSUE TITLE
rekey fails with no error message

### ISSUE THREAD

**Issue by rogerbinns** [utelle/SQLite3MultipleCiphers#164]
I was trying to change the page size for testing.  The `rekey` pragma fails with `SQLITE_ERROR` and doesn't set any error message.

````
import apsw

con = apsw.Connection("testdb")
con.pragma("key", "hello")
con.execute("create table x(y); insert into x values(randomblob(32768))")

# rekey
con.pragma("cipher", "aes128cbc")
con.pragma("legacy", "1")
con.pragma("legacy_page_size", 16384)
con.pragma("rekey", "hello")
````

````
Traceback (most recent call last):
  File "/space/mc/issue.py", line 11, in <module>
    con.pragma("rekey", "hello")
  File "src/cursor.c", line 959, in APSWCursor_execute.sqlite3_prepare_v3
    AddTraceBackHere(__FILE__, __LINE__, "APSWCursor_execute.sqlite3_prepare_v3", "{s: O, s: O}",
apsw.SQLError: SQLError: SQL logic error
````

**Comment by utelle** [comment]
> I was trying to change the page size for testing.

Changing the page size is not possible for encrypted databases. The only way to change the page size is to decrypt the database, change the page size, run vacuum, and to reencrypt the database.

The real problem is that changing the page size and then running `VACUUM` for an encrypted database results in a corrupted database. `VACUUM` does not report an error.

AFAICR prior SQLite versions (before the `SQLITE_HAS_CODEC` feature was removed) included a check for encrypted databases, but now this is no longer the case.

> The `rekey` pragma fails with `SQLITE_ERROR` and doesn't set any error message.

If I use the pragma in a SQLite shell, error messages are reported. But maybe the messages don't come from the pragma return value, but from the last error message. I have to check the code of the pragma handling.

**Comment by rogerbinns** [comment]
> Changing the page size is not possible for encrypted databases

I was specifically changing the legacy page size cipher parameter.  This was doing brute force testing constantly changing parameters and rekeying.  

`SQLITE_ERROR` is definitely being returned by executing the pragma - ie the call the `sqlite3_prepare_v3` is returning `SQLITE_ERROR` and `sqlite3_errmsg` is returning `SQL logic error`.  `sqlite3_log` was called with `SQL logic error in "pragma rekey='hello'"`. which you were probably seeing.

Just like with the backup case refusing bad operations is a good idea, and a helpful error message is ideal.

**Comment by utelle** [comment]
Commit 02b69ad7418a59530253d1ed5061a94b0016ca49 enforces the return of correct error messages.

Additionally, legacy page size and plaintext header size are now checked for valued values.
