### ISSUE TITLE
Derialized database is claimed to be in-memory or temporary

### ISSUE THREAD

**Issue by rogerbinns** [utelle/SQLite3MultipleCiphers#169]
````
import apsw

con = apsw.Connection("testdb")

con.execute("create table x(y); insert into x values(randomblob(65536))")
# encrypt
con.pragma("hexrekey", "aabbccdd")
# serialize
before = con.serialize("main")
# copy of data
data = con.execute("select * from x").get
# deserialze the same data
con.deserialize("main", before)
# rekey
con.pragma("hexrekey", "aabbccdd")
````

````
$ rm testdb* ; python issue.py 
APSW debug build: missing sys.apsw_fault_inject_control
Traceback (most recent call last):
  File "/space/mc/issue.py", line 15, in <module>
    con.pragma("hexrekey", "aabbccdd")
  File "src/cursor.c", line 169, in resetcursor
    AddTraceBackHere(__FILE__, __LINE__, "resetcursor", "{s: i}", "res", res);
apsw.SQLError: SQLError: Rekeying not supported for in-memory or temporary databases.
````

**Comment by utelle** [comment]
> Deserialized database is claimed to be in-memory or temporary

The deserialized database **_is_** actually an in-memory database. That is, what `sqlite3_deserialize` does. The comment in the source code just above the implementation of this function reads:

> > Convert zSchema to a MemDB and initialize its content

And the first paragraph in the [`sqlite3_deserialize` documentation](https://sqlite.org/c3ref/deserialize.html) tells you the same.

Function `sqlite3_serialize` retrieves the _decrypted_ (**!**) database content, and function `sqlite3_deserialize` restores it as an in-memory database.

And therefore `PRAGMA rekey` fails.

So, this is expected behaviour.

Sure, it would be nice to be able to seralize a database in encrypted state and restore it in encrypted state, but at least with the implementation coming with the public SQLite distribution this is not possible.

**Comment by rogerbinns** [comment]
I've done some more testing.  If the deserialized database is written to a separate file, and that file is opened as normal then everything is fine, with reserved bytes being non-zero as expected.

If the deserialized database overwrites an existing open connection, then as you state, it is really using memory until the connection is closed.  For example you can't change the journal mode away from `memory`.  

Serializing encrypted state can be done by flushing journals and then copy the underlying files.

**Comment by utelle** [comment]
> I've done some more testing. If the deserialized database is written to a separate file, and that file is opened as normal then everything is fine, with reserved bytes being non-zero as expected.

Yes, since `sqlite3_serialize` returns an exact image of the database file this works, of course.

> If the deserialized database overwrites an existing open connection, then as you state, it is really using memory until the connection is closed. For example you can't change the journal mode away from `memory`.

More important is that the serialized database should not be in WAL mode. If it was, the database image must be tweaked to force default journal mode.

> Serializing encrypted state can be done by flushing journals and then copy the underlying files.

IMHO a better approach would be to use either SQLite backup methods or `vacuum into`.
