### ISSUE TITLE
sqlite3_rekey to re-encrypt a db

### ISSUE THREAD

**Issue by anperch** [utelle/SQLite3MultipleCiphers#17]
Hi,

I have an pure Win32 API C application currently using sqleet.
While trying to move to this library (testing), I noticed the following:

Calling sqlite3_rekey(db, "", 0), then sqlite3_rekey(db, newPW, strlen(newPW)) in sequence gives SQLITE_OK for both, but I loose control of the database, meaning the new password cannot decrypt the db anymore.
If I insert the sequence of closing and reopening the db, then it is fine.

So :

{
sqlite3_rekey(db, "", 0) <- SQLITE_OK // decrypt db
...
sqlite3_rekey(db, newPW, strlen(newPW)) <- SQLITE_OK  // reencrypt db
}

-> ok with sqleet, but not with SQLite3MultipleCiphers, **in spite of both SQLITE_OK**.
No access to db with the new password.

But :

{
sqlite3_rekey(db, "", 0) <- SQLITE_OK
sqlite3_close(db);                           <- NEW
sqlite3_open(DbName, &db);                   <- NEW
sqlite3_rekey(db, newPW, strlen(newPW)) <- SQLITE_OK
}

-> ok now with with SQLite3MultipleCiphers

Is the closing and reopening between 2 calls to sqlite3_rekey mandatory , or it this a bug ? 

Anyway thanks for the impressive good job !	

My config :

IDE : CodeBlocks
Compiler : GCC 10.2 64bit from winlibs.com
Libraries : most recent of Sqleet and SQLite3MultipleCiphers as of 11/8/2020

**Comment by utelle** [comment]
Thanks for reporting the issue. I will look into it. However, that may take a while. I made a few experiments myself, of which some failed and some not. That is, I have to further investigate what's going on under the hood.

Closing and reopening between calls to `sqlite3_rekey` should not be necessary. However, rekeying a database **is** a critical operation and definitely no other process should be connected to the same database while rekeying takes place.

At a higher level the rekeying process of sqleet and SQLite3MultipleCiphers are very similar. However, in SQLite3MultipleCiphers accessing the database is now done via VFS, while sqleet still uses the CODEC API which is no longer part of SQLite3 since February 2020. Whether this is the reason for the behaviour you observed, I don't know yet.

**Comment by anperch** [comment]
Thanks for your quick answer. No hurry for me, though.
BTW,  I am using this config for the test  : sqlite3mc_config(db, "default:cipher", CODEC_TYPE_CHACHA20);

**Comment by utelle** [comment]
Keep in mind that you also need to use/set the `legacy` configuration parameter, if you want full compatibility with the _original_ **sqleet** encryption, because **sqleet** fully encrypts the database header, while **SQLite3MultipleCiphers** does not, if not set to legacy mode. 

The official SQLite3 encryption extension (SEE) does not encrypt bytes 16 to 23 of the database header, because SQLite3 accesses those bytes, before any encryption extension has a chance to intercept. For compatibility reasons **SQLite3MultipleCiphers** also doesn't encrypt those bytes, unless legacy mode is selected.

**Comment by anperch** [comment]
Here is a more accurate description of what happens in my app.
- the password change is done inside a dialog, and right after the change, I can continue to work with the app, reload new data and browse the db properly.  So it is clear at this point that some decryption happens.
- It is only when closing et reopening the application that the password is not recognized.

**Comment by utelle** [comment]
Thanks for the details. As said, I will look into it.

The problem could possibly be related to page caching somehow. - And it seems that the problem does not surface if an already encrypted database is re-encrypted with a new key. Up to now I only observed problems, when removing a password and then rekeying with a new password.

**Comment by lke-v** [comment]
Since I consider moving to your library (thanks for the great work!!) I'd like to check if I understand correctly:

- this problem may not only occur for sqleet but for any cipher? 
- rekeying via PRAGMA rekey is probably affected just as well as the C API call?

Specifically, I'd like to both rekey and change the cipher for existing databases using the weak RC4 encryption. I imagined doing so by just calling `PRAGMA rekey=''; PRAGMA cipher='chacha20'; PRAGMA rekey='newpassword'`. Will that potentially suffer from the same problem?

**Comment by utelle** [comment]
> Since I consider moving to your library (thanks for the great work!!)

Thanks. The VFS based implementation of the encryption extension is relatively new and definitely not yet in as widespread use as its predecessor. Therefore it is likely that the code still contains bugs, although I haven't received many bug reports up to now.

> I'd like to check if I understand correctly:
> 
> * this problem may not only occur for sqleet but for any cipher?

Well, my analysis is not yet complete. As far as I can tell right now, the problem seems to surface only, if rekeying from _"unencrypted"_  or _"cipher without HMAC"_ (**aes128cbc, aes256cbc, rc4**) to a _"cipher with HMAC"_ (**chacha20, sqlcipher**) or vice versa. That is, if the rekeying process needs to use a special vacuum procedure, the problem can occur.

> * rekeying via PRAGMA rekey is probably affected just as well as the C API call?

Yes.

However, if the database is closed and reopened after each rekeying operation, then all seems to work as expected. Maybe the problem has something to do with database page caching. I still have to further investigate the issue.

> Specifically, I'd like to both rekey and change the cipher for existing databases using the weak RC4 encryption. I imagined doing so by just calling `PRAGMA rekey=''; PRAGMA cipher='chacha20'; PRAGMA rekey='newpassword'`. Will that potentially suffer from the same problem?

**rc4** is a cipher _without_ HMAC, while **chacha20** is a cipher _with_ HMAC. Therefore the process is potentially affected. However, the step `PRAGMA rekey='';` is not necessary - that is, intermediately unencrypting the database is not required. You can rekey an **rc4** encrypted database immediately to a **chacha20** encrypted database in a single rekeying operation (`PRAGMA cipher='chacha20'; PRAGMA rekey='newpassword'`). And if you close the database after rekeying, before further modifying it, you should be on the safe side for now.

I will try to fix the issue, so that closing the database after rekeying will not be necessary, but that will take some time, because I have to fully understand what exactly is causing the problem, first.

**Comment by lke-v** [comment]
Thanks for the clarification!
Given my context using Entity Framework on top of SQLite, and the rekeying being part of an EF migration I doubt that I could easily force closing the database at that specific point since the connection is maintained in a connection pool maintained by EF. Still could disable pooling as a last resort.
However, going into production is still a few months ahead, so I hope for a fix by then.

**Comment by utelle** [comment]
I will do my best to solve the problem in the near future.

Another option to convert database files from **rc4** to **chacha20** would be to use the SQLite command shell (pre-built binaries are available). However, I'm pretty confident that the issue can be fixed in time.

**Comment by utelle** [comment]
I think I have tracked down the problem. It seems to be linked to SQLite's handling of the number of reserved bytes per page (used for HMACs by the encryption extension). 

Up to SQLite version 3.31.x it was possible to set the number of reserved bytes per page unconditionally. This made it possible to reclaim the reserved bytes per page when decrypting a database file. And **sqleet** as well as **wxSQLite3** (the predecessor of **SQLite3MultipleCiphers**) made use of this feature.

However, since SQLite version 3.32.0 the behavior of SQLite changed: now SQLite refuses to reduce the number of reserved bytes per page. Only increasing the number of reserved bytes is supported. If a reduced number of reserved bytes is requested, SQLite silently uses the original number of reserved bytes. For the rekeying procedure of **SQLite3MultipleCiphers** this doesn't matter as long as the database is closed immediately after rekeying, but causes the observed problems, if the database file is not closed.

Unfortunately I was not aware of this behavioral change. There are now several options how to solve the issue:

1. **Implement a method which allows to reduce the number of reserved bytes per page**. This approach would be the most convenient, but maintaining compatibility with future SQLite versions could be harder to achieve.

1. **Accept the behavioral change** and keep the number of reserved bytes per page even when decrypting a database. For the latter use case this would waste up to 80 bytes per database page depending on the chosen cipher scheme. Additionally, this could cause problems on switching from a cipher scheme to another one which uses less reserved bytes.

3. **Restrict rekeying to use cases for which the number of reserved bytes does not change**. In use cases where the number of reserved bytes per page **does** change, rekeying is done into a separate database file. This approach would break applications which rely on in-place rekeying. In fact, this approach is chosen by **SQLCipher**, for example.

I tend to choose the first mentioned approach, but I haven't yet come to a final conclusion.

**Comment by utelle** [comment]
Commit 3fa3256b7d074b1487d69097353cbb0e83cf1f44 implements the first approach mentioned in my previous post. This should fix this issue.

**Comment by anperch** [comment]
_Brilliant !_
The database is now accessible after the previously problematic code sequence.
Any idea why the shrinking of the reserved bytes was removed ?

**Comment by utelle** [comment]
> Any idea why the shrinking of the reserved bytes was removed ?

Well, in fact this feature was not removed. Officially, it was never there. The original SQLite code in prior versions did not support shrinking the number of reserved bytes per page either. With a modified version of the VACUUM procedure it worked, however, because the reduced number of reserved bytes was accepted. Since version 3.31.0 a reduced number of reserved bytes is silently ignored.

There is a comment in the original SQLite source code telling _"The amount of reserve can only grow - never shrink."_. However, there is no explanation given, why the SQLite developers say that.

My guess is the following: _reserved space_ is used by dedicated SQLite extensions, for example, encryption extensions. A SQLite user might have more than one extension in use, which reserve space per page. That is, the already reserved space might be in use by another extension and therefore it might not be a good idea to remove the reserved space.

However, in the public source code of SQLite there exists only a single extension which makes use of reserved space, namely the extension _ChecksumVFS_, but it is not compatible with any other extension using reserved space.

**SQLite3MultipleCiphers** isn't compatible either with other extensions which make use of reserved space. Therefore it made sense in my humble opionion to reclaim reserved space if it is no longer used for encryption.

If more than one extension want to make use of reserved space, I think, they need to know of each other, so that it is always clear, which part of the reserved space is used by which extension. However, this is a special use case, I haven't seen in the wild yet.

**Comment by lke-v** [comment]
> Commit [3fa3256](https://github.com/utelle/SQLite3MultipleCiphers/commit/3fa3256b7d074b1487d69097353cbb0e83cf1f44) implements the first approach mentioned in my previous post. This should fix this issue.

Thanks for the quick fix and for choosing an approach which still allows to change ciphers 👍
