### ISSUE TITLE
How to compile Windows VS08 version？

### ISSUE THREAD

**Issue by vagabond1132** [utelle/SQLite3MultipleCiphers#170]
I need a static library for this project    [SQLite3MultipleCiphers](https://github.com/utelle/SQLite3MultipleCiphers) 1.8.6   

How can I make modifications? I need help。

release-mt/md.lib

**Comment by utelle** [comment]
_Visual C++ 2008_ (aka _Visual Studio 2008_) was released in November 2007. That is, it is a really **old** and **outdated** compiler. _SQLite3 Multiple Ciphers_ was never tested with _Visual C++ 2008_. I would strongly recommend that you upgrade your compiler to _Visual C++ 2015_ or higher.

If you really can't avoid to use _Visual C++ 2008_, you could use [premake5](https://github.com/premake/premake-core/releases) to generate build files for _Visual C++ 2008_. However, using those build files will not work out of the box, because _Visual C++ 2008_ doesn't support property files (`.props`). Thus, you will have to adjust the defined preprocessor symbols to not use variables (which are defined in the property file).

Additionally, you will have to adjust several source files, because the C standard supported by _Visual C++ 2008_ requires that **all** variables are defined at the beginning of a block. This is not always the case in the current code base.

I close this issue, because I don't intend to add support for such outdated compilers.
