### ISSUE TITLE
project for vs2008

### ISSUE THREAD

**Issue by 15589957397** [utelle/SQLite3MultipleCiphers#171]
VS2008 cannot build; could you provide the version of VS2008?"

**Comment by utelle** [comment]
_Visual C++ 2008_ (aka _Visual Studio 2008_) was released in November 2007. That is, it is a really old and outdated compiler. _SQLite3 Multiple Ciphers_ was never tested with _Visual C++ 2008_. I would strongly recommend that you upgrade your compiler to _Visual C++ 2015_ or higher. Remember that the most recent _Visual C++_ version is _Visual C++ 2022_.

If you can't avoid using _Visual C++ 2008_, see [my comment to issue 170](https://github.com/utelle/SQLite3MultipleCiphers/issues/170#issuecomment-2256302780).

I close this issue, because I don't intend to add support for such outdated compilers.
