### ISSUE TITLE
SQLCipher compatibility with WAL

### ISSUE THREAD

**Issue by rgroenewoudt** [utelle/SQLite3MultipleCiphers#174]
I'm currently looking into replacing SQLCipher but I'm running into issues when the journal is set to WAL. Without WAL it works.

SQLCipher 4.5.2, based on SQLite 3.39.2
Connection string: `Data Source=test1.db;Cache=Private;Pooling=False`
Running pragma's on SQLCipher:
```
PRAGMA key = 'MYPASS';
PRAGMA journal_mode = WAL;
SELECT count(*) FROM sqlite_master;
```

Opening the same database with SQLite3MC fails with an error `SQLite Error 26: 'file is not a database'.`
SQLite3MC 3.46.0
Pragma's:
```
PRAGMA cipher = 'sqlcipher';
PRAGMA key = 'MYPASS';
PRAGMA journal_mode = WAL;
SELECT count(*) FROM sqlite_master;
```

If I leave out the journal_mode in both, then it works.

I'm not on the latest version of SQLite3MC (I'm using https://github.com/ericsink/SQLitePCL.raw) but the latest changes doesn't seem to be related.

Any help would be appreciated to debug this.

**Comment by utelle** [comment]
> I'm currently looking into replacing SQLCipher but I'm running into issues when the journal is set to WAL. Without WAL it works.

Actually, your problem has nothing to do with the journal mode - see below.

> SQLCipher 4.5.2, based on SQLite 3.39.2 Connection string: `Data Source=test1.db;Cache=Private;Pooling=False` Running pragma's on SQLCipher:
> 
> ```
> PRAGMA key = 'MYPASS';
> PRAGMA journal_mode = WAL;
> SELECT count(*) FROM sqlite_master;
> ```

Setting journal mode WAL results in a non-empty database file, although you did not create a database schema (by creating tables, inserting data etc). However, not setting journal mode WAL - and thus keeping the default journal mode DELETE - results in an empty database file (zero length).

> Opening the same database with SQLite3MC fails with an error `SQLite Error 26: 'file is not a database'.` SQLite3MC 3.46.0 Pragma's:
> 
> ```
> PRAGMA cipher = 'sqlcipher';
> PRAGMA key = 'MYPASS';
> PRAGMA journal_mode = WAL;
> SELECT count(*) FROM sqlite_master;
> ```

This is not surprising, because you want to open a database file created by SQLCipher. To make that work you have to tell that to SQLite3MC using the following pragma - assuming that you use SQLCipher version 4 -:

```SQL
PRAGMA legacy=4;
```

This signals to SQLite3MC that a SQLCipher legacy mode should be used. For more information about legacy modes see [Legacy Cipher Modes](https://utelle.github.io/SQLite3MultipleCiphers/docs/ciphers/cipher_legacy_mode/) in the SQLite3MC documentation.

The order of pragmas matters. The following sequence should do the trick:

```SQL
PRAGMA cipher = 'sqlcipher';
PRAGMA legacy=4;
PRAGMA key = 'MYPASS';
PRAGMA journal_mode = WAL;
SELECT count(*) FROM sqlite_master;
```

> If I leave out the journal_mode in both, then it works.

Not really. It works because the database file is empty. If you would insert data from SQLite3MC here, the resulting database file would not be compatible with the original SQLCipher, because the non-legacy mode is used.

> I'm not on the latest version of SQLite3MC (I'm using https://github.com/ericsink/SQLitePCL.raw) but the latest changes doesn't seem to be related.

You are right.

**Comment by rgroenewoudt** [comment]
Great, that was the problem. Thank you for your help.
