### ISSUE TITLE
Backup / Restore API Status 

### ISSUE THREAD

**Issue by Willena** [utelle/SQLite3MultipleCiphers#21]
Hi Utelle, 

Are the information displayed in the old readme for the backup / restore api (https://github.com/utelle/wxsqlite3/tree/0b3cad24b38406927568b9997302f6fe5642cc9e/sqlite3secure#backupapi) still applicable to this "new and reworked" version of the library ? Are there any major changes ?

**Comment by utelle** [comment]
In principle, the information about the backup / restore API given in the old readme is still correct. The backup / restore API of SQLite has the restriction that the number of reserved bytes can not be changed. Therefore it is strongly recommended to use the same cipher for both, source and target.

The new implementation should work in the same way as the previous implementation, since the encryption methods have not changed. However, I have to admit that I haven't tested yet the backup / restore API with different ciphers for source and target using the new implementation. And as said, it should be strongly discouraged to use the backup / restore API with different ciphers for source and target.

If one really needs to convert from one cipher to another, one should use the new form of the `VACUUM` SQL command with the `INTO` clause. For the target database any cipher scheme can be used. However, this approach is slower than the backup / restore API.

**Comment by Willena** [comment]
Thanks for the information :)
