### ISSUE TITLE
Whether the iOS system is supported

### ISSUE THREAD

**Issue by WalkManA** [utelle/SQLite3MultipleCiphers#30]
cross compile with clang in mac for IOS,sqlite3_prepare_v2 return error

**Comment by utelle** [comment]
Unfortunately you don't show details about the errors which occurred. Please show the error messages you receive.

Since I don't have an iOS system for testing myself, I can only guess. Most likely the compile fails due to missing or mismatching compiler options regarding native AES support. In principal, Sqlite3 Multiple Ciphers should work on iOS, too.

**Comment by utelle** [comment]
Closing ... without further information it is not possible to investigate the issue (if it actually is one).

**Comment by Nailik** [comment]
Hi,
i had the issue that it didn't compile on MacOs for iOS because `<sys/random.h>` could not be found.
What exactly is it used for?
Because when i literraly comment out the line it still compiles, seems to recrypt and all other things seem to work.

**Comment by utelle** [comment]
It would have been better to open a new issue instead of hijacking an unrelated one.

> i had the issue that it didn't compile on MacOs for iOS because `<sys/random.h>` could not be found. What exactly is it used for? Because when i literraly comment out the line it still compiles, seems to recrypt and all other things seem to work.

Unfortunately I can't remember the exact circumstances why this include was introduced. I assume back then it was necessary to access the definition of the function `getentropy`. Maybe this function is now defined elsewhere in another header file.

**Comment by utelle** [comment]
According to [this](https://keith.github.io/xcode-man-pages/getentropy.2.html) or [this](https://opensource.apple.com/source/xnu/xnu-6153.41.3/bsd/man/man2/getentropy.2.auto.html) description the function `getentropy` was/is defined in `<sys/random.h>`.

Which compiler do you use? Maybe it depends on the compiler which include files are available and where `getentropy` is defined.

**Comment by Nailik** [comment]
First i generated the amalgamation files and then i used https://github.com/swiftlyfalling/SQLiteLib to build the library.
I use the flags from sqlcipher -DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=3 -DSQLCIPHER_CRYPTO_CC -DNDEBUG 
and -maes but i am not sure if the last one has any effect.

**Comment by utelle** [comment]
> First i generated the amalgamation files and then i used https://github.com/swiftlyfalling/SQLiteLib to build the library.

I don't have an iOS system at hand, so I can't test anything on my own. Maybe it depends on the XCode version. Which one do you use?

> I used the flags from sqlcipher -DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=3 -DSQLCIPHER_CRYPTO_CC -DNDEBUG and -maes but i am not sure if the last one has any effect.

This doesn't make much sense. SQLite3MultipleCiphers itself doesn't need `-DSQLITE_HAS_CODEC` and `-DSQLCIPHER_CRYPTO_CC`.
