### ISSUE TITLE
Opening an unencrypted database while using `PRAGMA key`

### ISSUE THREAD

**Issue by m4heshd** [utelle/SQLite3MultipleCiphers#43]
I've been setting up and testing [`better-sqlite3-multiple-ciphers`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers) with my existing projects and have hit a slight bump on the road. This could be the intended behavior but very problematic in my use case.

As I've mentioned in #42, my project previously used `sqleet` and this application is designed to read both encrypted and unencrypted databases depending on the scenario but using the same codebase. So `PRAGMA key='xxxxx'` statement is used in the  source regardless of encryption status. Worked perfectly fine on both types of DBs with `sqleet`. But when using `sqlitemc` an attempt to open an unencrypted DB while using `PRAGMA key` results in the following error.

```bash
SqliteError: unsupported file format
```

However it doesn't throw this error if the DB is empty (0kb). Is there any way to change this behavior to my expectation? If not, is there any specific cipher I can use other than `chacha20` to make it work? I'm trying to avoid a massive amount of refactoring to my code.

**EDIT:**
Just saw #7. So what I'm thinking now is, "Should `PRAGMA key` be encrypting the DB at any point?". In my experience, only `PRAGMA rekey` should be able to encrypt the DB (as `sqleet` does) because it makes sense. Using `PRAGMA key` statement for both tasks on different scenarios generates a bit of confusion and lead to possible unintended circumstantial bugs in applications. But that's just my take. No idea if you intended for it to behave that way to match some compatibility problem. Does `SEE` work that way? Documentation is not very clear on that.

**Comment by utelle** [comment]
> As I've mentioned in #42, my project previously used `sqleet` and this application is designed to read both encrypted and unencrypted databases depending on the scenario but using the same codebase. So `PRAGMA key='xxxxx'` statement is used in the source regardless of encryption status.

IMHO it is a design flaw to use `PRAGMA key='passphrase'` on an unencrypted database, because you are telling the library that the database file **is in fact encrypted**.

> Worked perfectly fine on both types of DBs with `sqleet`.

I have not tested this. However, if you can specify a non-empty passphrase for an unencrypted database and can then really access the unencrypted database successfully with `**sqleet**, this indicates a bug in **sqleet** IMHO.

> But when using `sqlitemc` an attempt to open an unencrypted DB while using `PRAGMA key` results in the following error.
> 
> ```shell
> SqliteError: unsupported file format
> ```

This is expected behaviour.

> However it doesn't throw this error if the DB is empty (0kb).

This is expected behaviour, too.  Specifying a passphrase for a new (empty) database immediately enables encryption.

> Is there any way to change this behavior to my expectation? If not, is there any specific cipher I can use other than `chacha20` to make it work? I'm trying to avoid a massive amount of refactoring to my code.

No. This behaviour does not depend on a specific cipher.

> **EDIT:**
> Just saw #7. So what I'm thinking now is, "Should `PRAGMA key` be encrypting the DB at any point?". In my experience, only `PRAGMA rekey` should be able to encrypt the DB (as `sqleet` does) because it makes sense. Using `PRAGMA key` statement for both tasks on different scenarios generates a bit of confusion and lead to possible unintended circumstantial bugs in applications. But that's just my take. No idea if you intended for it to behave that way to match some compatibility problem. Does `SEE` work that way? Documentation is not very clear on that.

The [official SQLite Encryption Extension (SEE)](https://sqlite.org/see/) works exactly in this way. If you specify a passphrase for an empty database, the database will be created as an encrypted database with the given passphrase. 

Using `PRAGMA key` indicates that the database is encrypted. In fact, no distinction is made between empty (new) or non-empty (existing) databases is made. In case of a new empty database there is no content that possibly could conflict with the given encryption passphrase. An error occurs only, if there is already content in the database, either unencrypted or encrypted with a different passphrase.

**Comment by m4heshd** [comment]
> if you can specify a non-empty passphrase for an unencrypted database and can then really access the unencrypted database successfully with `sqleet, this indicates a bug in sqleet IMHO.

You think so? 🤔 But have to admit it's really convenient though. Because the only way to know if a DB is encrypted is to set `PRAGMA key` and then to do a query and see if the DB throws an error right? And even then a corrupted database could throw the same error.

> No. This behaviour does not depend on a specific cipher.

Ouch. That's gonna hurt me real bad. 😬

> The official SQLite Encryption Extension (SEE) works exactly in this way.

That was my guess. A really long time ago I used an extension called `sqlite-crypt` which had the very same behavior.

Would it take a lot of effort to remove the encryption functionality from `PRAGMA key` and force it to simply be ignored if the DB is unencrypted? If it's not then I'll happily dive into the code and gonna try to maintain a fork of `sqlitemc`. _(just to avoid the pain of refactoring my application because can't afford to do so at this moment)_. But if _refactoring `sqlitemc` > refactoring my app_ I'd rather adapt.

**Few unrelated questions:**

1. Is **`sqlite3_shutdown()`** necessary? If so, I'm gonna have to write node bindings for that.
2. How come DB4S SQLCipher (4.4.2) fails to open a `sqlitemc` sqlcipher encrypted DB? Possible version difference or the algorithm itself?
3. What cipher would you recommend? _(most reliable and most efficient)_

**Comment by utelle** [comment]
While investigating this issue I stumbled about the fact that the current implementation of `PRAGMA key` returns an _SQL Logic Error_ if an empty passphrase is specified. Although I wouldn't call this a _real_ bug, it is at least inconvenient if an application simply wants to try to access a database with or without encryption.

Therefore I adjusted the implementation in commit 54274607da1534d178ad053039e84ff682456873, so that specifying an empty passphrase works as expected. This allows to issue more than one `PRAGMA key` command without requiring to reopen the database connection.

Additionally, I'd like to point out that you have to take appropriate actions if your goal is to access legacy _sqleet_ databases. Please read the section about [**legacy cipher modes**](https://utelle.github.io/SQLite3MultipleCiphers/docs/ciphers/cipher_legacy_mode/) in the **SQLite3 Multiple Ciphers** documentation.

**Comment by m4heshd** [comment]
> I adjusted the implementation in commit 5427460, so that specifying an empty passphrase works as expected.

Thank you for taking the time and correcting the behavior.

> Please read the section about legacy cipher modes in the SQLite3 Multiple Ciphers documentation.

I was aware of that and luckily my application isn't distributed yet so I simply migrated the data.

**Comment by utelle** [comment]
> > if you can specify a non-empty passphrase for an unencrypted database and can then really access the unencrypted database successfully with `sqleet, this indicates a bug in sqleet IMHO.
> 
> You think so? 🤔

Yes. If a **non-empty** passphrase is specified for an unencrypted database the library must throw an error.

However, you may retry to access the database with an **empty** passphrase. I have to admit that that was not possible up to today (see my previous post), but I adjusted the implementation, so that issuing a `PRAGMA key` command with an empty passphrase is possible and works as expected.

> But have to admit it's really convenient though. Because the only way to know if a DB is encrypted is to set `PRAGMA key` and then to do a query and see if the DB throws an error right?

Well, you could do it the other way around. First, access the database without using `PRAGMA key` . If that fails chances are high that the database is encrypted.

> And even then a corrupted database could throw the same error.

Sure. You would also get such an error if the database was encrypted with a different cipher scheme.

> > No. This behaviour does not depend on a specific cipher.
> 
> Ouch. That's gonna hurt me real bad. 😬

With the now available implementation (although not yet officially released) the pain should be bearable.

> > The official SQLite Encryption Extension (SEE) works exactly in this way.
> 
> That was my guess. A really long time ago I used an extension called `sqlite-crypt` which had the very same behavior.

AFAICT most, if not all SQLite encryption extensions have this behaviour.

> Would it take a lot of effort to remove the encryption functionality from `PRAGMA key` and force it to simply be ignored if the DB is unencrypted?

The modification I have applied today is all I can do for you. The new implementation allows to specify a `PRAGMA key='passphrase';` command (with non-empty passphrase), check whether accessing the database works, and if not, to re-issue a `PRAGMA key='';` command (with an _empty_ passphrase) to check for an unencrypted database.

> If it's not then I'll happily dive into the code and gonna try to maintain a fork of `sqlitemc`. _(just to avoid the pain of refactoring my application because can't afford to do so at this moment)_. But if _refactoring `sqlitemc`  refactoring my app_ I'd rather adapt.

Of course, you are always free to create a fork and tweak the code to your liking.

> **Few unrelated questions:**
> 
> 1. Is **`sqlite3_shutdown()`** necessary? If so, I'm gonna have to write node bindings for that.

Yes, if you want to avoid memory leaks by all means.  IMHO not freeing the dynamic SQLite VFS data structures on closing an application is usually not critical, because typically the OS reclaims the memory after an application has been terminated. However, for embedded systems it might be important to avoid memory leaks under all circumstances.

> 2. How come DB4S SQLCipher (4.4.2) fails to open a `sqlitemc` sqlcipher encrypted DB? Possible version difference or the algorithm itself?

If the configuration parameter `legacy=1` is not used when creating an encrypted database with **SQLite3 Multiple Ciphers**, then the resulting database file will not be compatible with legacy applications (like DB4S) - please refer to [legacy cipher modes](https://utelle.github.io/SQLite3MultipleCiphers/docs/ciphers/cipher_legacy_mode/) for more details. And of course you need to use the matching cipher: DB4S uses SQLCipher, while the default of **SQLite3 Multiple Ciphers** is _ChaCha20_. However, you may adjust the defaults used by **SQLite3 Multiple Ciphers** at compile time by specifying preprocessor symbols.

> 3. What cipher would you recommend? _(most reliable and most efficient)_

Encryption always adds some runtime overhead, but in most use cases this is not critical.

**SQLite3 Multiple Ciphers** currently supports 5 different cipher schemes:

1. wxSQLite3 AES-128
2. wxSQLite3 AES-256
3. sqleet (ChaCha20-Poly1305)
4. SQLCipher (AES-128/AES-256)
5. System.Data.SQLite (RC4)

Schemes 1, 2, and 5 were added for compatibility with existing applications. They are not recommended for new applications.

Schemes 3 and 4 are both cryptographically reliable. Scheme 3 (ChaCha20) might be slightly more efficient, but the implementation of scheme 4 in **SQLite3 Multiple Ciphers** uses now native AES processor instructions where available, so that the performance decrease should usually almost neglectable.

**SQlite3 Multiple Ciphers** uses scheme 3 (ChaCha20) as the default, unless you change that.

**Comment by m4heshd** [comment]
Perfect. You've explained everything I needed to know. Again, very grateful for your time and effort. 🙏🏻 Closing the issue.

**Comment by utelle** [comment]
> Thank you for taking the time and correcting the behavior.

You are welcome.

> > Please read the section about legacy cipher modes in the SQLite3 Multiple Ciphers documentation.
> 
> I was aware of that and luckily my application isn't distributed yet so I simply migrated the data.

Personally, I recommend to use the default non-legacy modes of **SQLite3 Multiple Ciphers**. The difference between _non-legacy_ and _legacy_ is that certain bytes in the database header are **not encrypted** in _non-legacy_ mode. This has the advantage that SQLite can detect the database page size automatically.

However, it really depends on your use case: if your application needs to be compatible with other applications that use legacy ciphers (like original SQLCipher or sqleet), then you can compile **SQLite3 Multiple Ciphers** in such a way that the defaults are set according to your needs.

**Comment by m4heshd** [comment]
> However, it really depends on your use case

Fortunately my application doesn't expect any cross-compatibility so I'm sticking with non-legacy as you recommended. Thank you for educating me on that.

**Comment by utelle** [comment]
Sometimes tools like DB4S are useful for administrating databases. However, currently DB4S only has support for legacy SQLCipher encryption. As you well know it was [discussed](https://github.com/sqlitebrowser/sqlitebrowser/issues/1646) to add other encryption schemes, but up to now nothing happened.

Fortunately, there exist other tools like [SQLiteStudio](https://github.com/pawelsalawa/sqlitestudio) that support all cipher modes offered by **SQLite3 Multiple Ciphers**.

**Comment by m4heshd** [comment]
> Fortunately, there exist other tools like SQLiteStudio that support all cipher modes offered by SQLite3 Multiple Ciphers.

Yes. I used `SQLiteStudio` back and forth since a long time ago but always find myself coming back to DB4S because it just feels so familiar. 😁
