### ISSUE TITLE
Why the library compiled is so big about 9MB?

### ISSUE THREAD

**Issue by rookieWanZ** [utelle/SQLite3MultipleCiphers#46]
As Title shown, THANK YOU!
![123](https://user-images.githubusercontent.com/14228661/130348899-45085493-37bd-4890-aea5-cde870bfa1d2.png)

**Comment by utelle** [comment]
If I build the project with for example with `gcc (i686-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0` using the command `mingw32-make config=release_win32` the resulting DLL has a size of roughly 1.2 MB. For the debug configuration the DLL is bigger, of course, roughly 3 MB, because it contains debug symbols. That is, I can't confirm the library size you report. 

Since you don't show how you built your library, which compiler version you use, which configuration you chose, it is not possible to tell, why your resulting library is so big. Most likely your library object still contains all debug symbols.

If library size is a real concern, you can strip the symbols from the library object. Additionally, you can disable all SQLite extensions you don't need - this will reduce library size, too.

**Comment by rookieWanZ** [comment]
This is my mingw version
gcc version 10.3.0 (Rev2, Built by MSYS2 project)

And I try your option "make config=release_win32", it swells to 14M.....
Thank you for your reply!

**Comment by utelle** [comment]
Well, I installed the compiler you use, namely `gcc (Rev2, Built by MSYS2 project) 10.3.0`, on my development machine. However, if I now compile the library with this compiler, the size of the resulting DLL is again only about 1.5 MB.

IMHO the problem is related to your development environment and how you build the library. Please describe exactly which commands you are executing to build the SQLiteMultipleCiphers project, and show the compiler/linker output.

**Comment by rookieWanZ** [comment]
Sorry, I forget the detail that if I compile with Makefile after autoreconf and configure.
It reminds me losing "libld.a".
So I remove the "-ld" flag (in line 422/478/481 ) in the Makefile by hand and compile it agian it passed but has huge size.
And It works normal and I have checked the data by the SqliteStudio3.3 except the size issue. 


[complie_after remove -ld flag in  the makefile.log](https://github.com/utelle/SQLite3MultipleCiphers/files/7028204/complie_after.remove.-ld.flag.in.the.makefile.log)

[Makefile.txt](https://github.com/utelle/SQLite3MultipleCiphers/files/7028200/Makefile.txt)

**Comment by utelle** [comment]
The build files for autoconf/automake coming with _SQLite3 Multiple Ciphers_ are primarily meant for Linux platforms. I never used them together with MSYS2, although they should work with MSYS2, too - despite the linker option `-ldl` (which is not available on Windows platforms).

As far as I can tell from looking at the provided log file and makefile, your build process uses the compiler option `-g` which includes debug symbols. And most likely this causes the big size of the library file. The makefiles coming with _SQLite3 Multiple Ciphers_ specify this option (`-g`) only when compiling in debug mode.

**Comment by rookieWanZ** [comment]
> The build files for autoconf/automake coming with _SQLite3 Multiple Ciphers_ are primarily meant for Linux platforms. I never used them together with MSYS2, although they should work with MSYS2, too - despite the linker option `-ldl` (which is not available on Windows platforms).
> 
> As far as I can tell from looking at the provided log file and makefile, your build process uses the compiler option `-g` which includes debug symbols. And most likely this causes the big size of the library file. The makefiles coming with _SQLite3 Multiple Ciphers_ specify this option (`-g`) only when compiling in debug mode.

Ah......., That's a shame of me......, I haven't thought and checked this flag.....
Yes, when I remove the -g, It's 1.57MB now.
Thank you for your patient!!!!!
[! _ !]
