### ISSUE TITLE
No access to CHACHA20 encrypted db after update to 1.3.5

### ISSUE THREAD

**Issue by anperch** [utelle/SQLite3MultipleCiphers#56]
Hi,

I made a quick test with the new version 1.3.5 and I noticed that I could not access the databases encrypted with previous versions (CHACHA20).

- If I decrypt (with the old version) and encrypt again (with the new one), then it's fine.
- But now a tool like SQLite Studio 3.3.3 cannot read the newly encrypted files, which was fine before.

Is the compatibility broken with new version ?

Thanks for your comment

**Comment by utelle** [comment]
> I made a quick test with the new version 1.3.5 and I noticed that I could not access the databases encrypted with previous versions (CHACHA20).

Could you please describe in more detail which steps you took for your tests? Which previous version did you use? Which journal mode are you using?

> * If I decrypt (with the old version) and encrypt again (with the new one), then it's fine.

You mean, you had to use `PRAGMA rekey`?

> * But now a tool like SQLite Studio 3.3.3 cannot read the newly encrypted files, which was fine before.

SQLite Studio 3.3.3 is based on _SQLite3 Multiple Ciphers 1.2.4_. Versions below 1.3.2 had problems to operate in WAL journal mode. That is, databases with WAL journal files are not compatible. However, operation in DELETE journal mode (the default) was not affected. That is, there should not be any problems to access database files created by different versions.

> Is the compatibility broken with new version ?

No, the encryption algorithms for a database file itself didn't change. Encrypted databases should be accessible with all versions since the ChaCha20 cipher scheme was introduced in April 2018.

In case you used WAL journal mode, then you are affected by the problems mentioned above. However, these problems affected only the WAL journal files, not the main database file.

**Comment by anperch** [comment]
Sorry, my mistake. I was too quick. A wrong encryption was set  in my static lib following tests I did some time ago to remove unused encryption schemes.
So I can confirm that all is working fine for my applications and SQLite Studio access.
Sorry to waste your time and thanks again  for your great job.
