### ISSUE TITLE
make install does not copy header files

### ISSUE THREAD

**Issue by zitudu** [utelle/SQLite3MultipleCiphers#61]
The header files are not installed correctly after following the installation instructions of the document.

**Comment by utelle** [comment]
Thanks for reporting the issue and bringing it to my attention.

Actually, running `make install` currently doesn't install header files at all. The reason is that the _SQLite3MultipleCiphers_ header file `sqlite3mc.h` depends on the _SQLite_ header file `sqlite3.h`. Depending on how the build of _SQLite3MultipleCiphers_ is configured, installing the _SQLite_ header file `sqlite3.h` to a system directory could lead to problems like header file version mismatch with an installed _SQLite_ library.

I'm still undecided how to resolve the issue.

**Comment by zitudu** [comment]
Thank you for your reply. I'm new to C and can't offer useful advice.

My idea is that users should be aware of the effect of `make install`, and SQLite3MC should also ensure that it is installed correctly. Is it possible to check for file conflicts during `make install` and report errors to the user? In fact, SQLite3 is statically linked in most cases, so is SQLite3MC.

**Comment by utelle** [comment]
> My idea is that users should be aware of the effect of `make install`, and SQLite3MC should also ensure that it is installed correctly. Is it possible to check for file conflicts during `make install` and report errors to the user?

I guess I will have to restructure the directory layout to make it work.

> In fact, SQLite3 is statically linked in most cases, so is SQLite3MC.

The typical use case is to include the SQLite3MC source code amalgamation (just 2 files) with one's own project (as I did in my own [wxSQLite3](https://github.com/utelle/wxsqlite3) project, for example. Most likely that is the reason no one complained about the failing `make install` up to now.

**Comment by zitudu** [comment]
> The typical use case is to include the SQLite3MC source code amalgamation (just 2 files) with one's own project (as I did in my own wxSQLite3 project, for example.

This is a good example, I think I can use SQLite3MC in my program this way.

**Comment by utelle** [comment]
After commit 48f2fe1b25e183cd11418a9a8fa9df889193a2c4 this issue should now be fixed.
