### ISSUE TITLE
Non-legacy `SQLCipher` runs really slow on `armv7`

### ISSUE THREAD

**Issue by m4heshd** [utelle/SQLite3MultipleCiphers#63]
I've recently started testing SQLite3MC on `armv7` for [`better-sqlite3-multiple-ciphers`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers). At first the tests failed with `SQLCipher` because it was so slow that it ran past the timeout of 5 seconds.

You can take a look at [this run](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/runs/4939117800?check_suite_focus=true#step:4:566) and see that it took almost 12 seconds for each encryption and decryption task. I've tested this multiple times to check if the results were consistent. They were. `Sqleet` runs flawlessly and both ciphers are fine on `arm64`.

So what I wanted to know is if this was the expected outcome because I've seen that `SQLCipher` had this issue in the past.

FYI, these tests are running on Qemu containers by the way. That could've also affected the results. I never got to test on a physical device like a Raspberry Pi.

**Comment by utelle** [comment]
Let me first ask something about the issue's title. You explicitly wrote "**non-legacy** _SQLCipher_ runs ... slow ... on armv7". I strongly doubt that the performance depends on the _legacy_ mode. The _legacy_ mode only determines whether certain bytes of the SQLite header will be encrypted or not, that's all. That is, I would expect that **all** SQLCipher encryption variants will be slow.

> I've recently started testing SQLite3MC on `armv7` for [`better-sqlite3-multiple-ciphers`](https://github.com/m4heshd/better-sqlite3-multiple-ciphers). At first the tests failed with `SQLCipher` because it was so slow that it ran past the timeout of 5 seconds.

Unfortunately, I don't have access to a `armv7` device for testing. The _SQLCipher_ encryption scheme uses AES 256 Bit encryption. AES encryption is way slower than ChaCha20 encryption, especially if run on a device without AES hardware support. Another reason for being slow is the SQLCipher key derivation: SQLCipher version 4 set the iteration count for key derivation to 256.000 - that is, key derivation is slow by design. This makes opening an SQLCipher encrypted database a really expensive operation. 

> You can take a look at [this run](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/runs/4939117800?check_suite_focus=true#step:4:566) and see that it took almost 12 seconds for each encryption and decryption task. I've tested this multiple times to check if the results were consistent. They were. `Sqleet` runs flawlessly and both ciphers are fine on `arm64`.

1) It is to be expected that _sqleet_ (aka _ChaCha20_) is faster, because it doesn't use AES and the iteration count for key derivation is much lower than that for _SQLCipher_.
2) It would be necessary to determine if really **all** encryption steps are slow or if only **opening** the database is slow, but further access is normal.

> So what I wanted to know is if this was the expected outcome because I've seen that `SQLCipher` had this issue in the past.

I'd say the answer is _yes_: Opening an SQLCipher encrypted database is slow by design (due to the high iteration count for key derivation); AES encryption is slower than other encryption schemes, especially without AES hardware support.

> FYI, these tests are running on Qemu containers by the way. That could've also affected the results. I never got to test on a physical device like a Raspberry Pi.

As far as I know _Qemu_ can be really slow when emulating ARM on a non-ARM host. For reliable data you should test on ARM hardware.

**Comment by m4heshd** [comment]
> The legacy mode only determines whether certain bytes of the SQLite header will be encrypted or not

This I already knew but just mentioned that it's non-legacy for better clarity because I never tested legacy.

> AES encryption is slower than other encryption schemes, especially without AES hardware support.

This was my guess but never imagined that it could be like 25x slower. `Sqleet` truly is a much better option.

> As far as I know Qemu can be really slow when emulating ARM on a non-ARM host.

This was known to me as well but `arm64` somehow runs super fast. I guess that might have been because of the host's arch being 64-bit.

Closing the issue now that it's clear. Thank you for the fast response as always.
