### ISSUE TITLE
SQL logic error when using SQLite Shell and applying a key

### ISSUE THREAD

**Issue by Willena** [utelle/SQLite3MultipleCiphers#7]
While doing some tests with the sqlite shell (a fresh build on linux from the repository sources) I encounter an error when applying the key. 

Any ideas ? Is it a bug ? 
```console
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open test.db
sqlite> CREATE TABLE IF NOT EXISTS warehouses ( id integer PRIMARY KEY, name text NOT NULL, capacity real);
sqlite> pragma key='toto';
Error: SQL logic error
sqlite>
```

**Comment by utelle** [comment]
Since you did not get an error after entering the `CREATE TABLE` statement, I assume that either the database file `test.db` did not exist prior to the test or it was a plain, unencrypted database file.

If you want a newly created database to be encrypted, the statement `PRAGMA key=` has to be the very first action on the database. The statement `CREATE TABLE ...` triggers the creation of an unencrypted database. Therefore the statement `PRAGMA key=` fails, because the database is no longer empty and was already accessed. To encrypt an existing plain database, you have to use the statement `PRAGMA rekey=`.

Although it is not a bug, if statement `PRAGMA key=` fails under these circumstances, I will have to check whether a logic error is the behaviour to be expected. I will look into this.

In the prior version currently coming with wxSQLite3 the statement `PRAGMA key` returns `ok`, but the next action on the database fails with the error message `unsupported file format`. In the end this not any better than letting the statement `PRAGMA key=` fail immediately.

**Comment by Willena** [comment]
All database files do not exist prior using the shell. 
Using the `pragma rekey` and even when doing `pragma key` at the beginning the issue still exist.

```console
sqlite> .open test1.db
sqlite> pragma key='rr';
Error: SQL logic error
sqlite>
```
 
```console
sqlite> .open test.db
sqlite> CREATE TABLE IF NOT EXISTS warehouses ( id integer PRIMARY KEY, name text NOT NULL, capacity real);
sqlite> pragma rekey='rr' ;
Error: SQL logic error
sqlite>
```

I'm okay with the fact that `pragma key` fails immediately.

**Comment by utelle** [comment]
Executing `PRAGMA key` immediately after opening a database should work, of course. So, this is definitely a bug. I'll look into it and I will hopefully be able to fix it within the next couple of days.

As a workaround you could add the key as a URI parameter. That is, open the database file like this:
```sql
.open file:test1.db?key=rr
```

The new implementation is still experimental and it will take time to get all details right.

**Comment by utelle** [comment]
Commit 64f1eb62af3a9da64da4c318f51a648c336aa7b5 should fix the issue. Please give it a try.

`PRAGMA key` will now return the string `ok`, if the key could be set successfully. The behaviour is now the same as in prior versions. That is, if the wrong key was applied, then the next database operation will fail, not the `PRAGMA` statement.

**Comment by Willena** [comment]
Isn't it possible to make the `pragma` statement to fail only if the key cannot be applied ? I personally think this is a great behaviour.

I can confirm the issue is now fixed.

**Comment by utelle** [comment]
Thanks for testing and reporting back. So,  I guess, for now this issue can be closed. Reopen it if necessary.

Regarding your question: Returning `ok` if the pragma did not fail, and returning nothing if an error occurred, is in sync with the _official_ encryption API. The problem is that the underlying function `sqlite3_key` does not check whether the key is actually correct or not. This is done when data are read for the first time from the database file. However, this also follows SQLite`s philosophy. For example, after opening a new database file nothing is written to the file until the first SQL statement modifying the file has been actually executed.
