### ISSUE TITLE
request amalgamation to be added to git

### ISSUE THREAD

**Issue by baidwwy** [utelle/SQLite3MultipleCiphers#76]
I wish to use git submodule to sync

**Comment by utelle** [comment]
Sorry, the source amalgamation will not be added to the repository for obvious reasons: I would have to recreate the amalgamation every time after even the smallest change in one of the other source files. This would be cumbersome.

Actually, you can easily create the amalgamation yourself by using the [amalgamate script](https://github.com/utelle/SQLite3MultipleCiphers/blob/main/scripts/amalgamate.py).

If you intend to use _SQLite3 Multiple Ciphers_ as a git submodule you can simply compile the source file [sqlite3mc.c](https://github.com/utelle/SQLite3MultipleCiphers/blob/main/src/sqlite3mc.c) instead of the amalgamated source that is distributed in a release. This is just as good as using the amalgamation, because this file includes all other required source files.

**Comment by baidwwy** [comment]
All right!
