### ISSUE TITLE
tclsqlite extension

### ISSUE THREAD

**Issue by edoroe** [utelle/SQLite3MultipleCiphers#79]
Please, add build tclsqlite library for using this extension from tcl language.
Thanks!

**Comment by utelle** [comment]
According to the documentation for [Compiling the TCL interface](https://www.sqlite.org/howtocompile.html#compiling_the_tcl_interface) it should be sufficient to append the source file `tclsqlite.c` to the amalgamation. In principle, preparations for this process are already in place in source file `sqlite3mc.c` - the file `tclsqlite.c` will be included if the preprocessor symbol `TCLSH` is defined. Maybe it would be better to use something like `SQLITE_ENABLE_TCL`, because `TCLSH` is related to building a SQLite TCL shell.

However, I really don't know whether further steps are required, because I don't know much about TCL.

**Comment by edoroe** [comment]
Thanks!

**Comment by utelle** [comment]
Today I made a new release, [Version 1.4.4](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.4.4), that includes the source code of the TCL interface (eliminating the need to download additional files from the original SQLite distribution). Additionally, I changed the preprocessor symbol in `sqlite3mc.c`: the symbol `SQLITE_ENABLE_TCL` is now used.

I hope that helps a bit.
