### ISSUE TITLE
Segmentation Fault when rekeying the database

### ISSUE THREAD

**Issue by Willena** [utelle/SQLite3MultipleCiphers#8]
As before, I was playing around with the SQLiteShell (linux 64bit). I'm facing "Segmentation Fault" error when trying to rekey the database file. 

Below the steps I used:
```console
SQLite version 3.32.0 2020-04-29 01:09:46
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open file.db
sqlite> pragma key='rr';
ok
sqlite> CREATE TABLE contacts (contact_id INTEGER PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT NOT NULL,email TEXT NOT NULL UNIQUE, phone TEXT NOT NULL UNIQUE);
sqlite> select 1 from sqlite_master;
sqlite> pragma rekey='rrr';
Erreur de segmentation
```

**Comment by utelle** [comment]
Thanks for taking the time to test and to report bugs. I really appreciate that.

Most likely I introduced a bug while adapting the code to use the database filename to identify a database file handle. I will look into this.

**Comment by utelle** [comment]
Commit 4a6783368442d3cf4047e9911ed6442420888ce4 should fix the issue.

The bug was introduced in course of implementing the pragma handling. If the key length is given as `-1` it is assumed that the string is zero-terminated and that the key length should be determined from the string length. This was not done for function `sqlite3_rekey_v2`. Thus, the key length of `-1` was interpreted as an unsigned integer - that is, 4 GB password ... :boom:.

Now, function `sqlite3_rekey_v2` (just as function `sqlite3_key_v2`) calculates the key length from the string length, if the key length was specified as `-1`.

**Comment by Willena** [comment]
Thank you ! It seams to be working now.
