### ISSUE TITLE
How can I recover a corrupted encrypted db file

### ISSUE THREAD

**Issue by Jun90925** [utelle/SQLite3MultipleCiphers#86]
Normally we can recover a corrupted database file by using
`sqlite3 crrupted.d .recover | sqlite3 fixed.db`

But how to recover a database if it is encrypted ？

**Comment by utelle** [comment]
> Normally we can recover a corrupted database file by using `sqlite3 crrupted.d .recover | sqlite3 fixed.db`
> 
> But how to recover a database if it is encrypted ？

It's pretty much the same procedure:

`sqlite3mc_shell file:corrupted.db?key=passphrase .recover | sqlite3mc_shell file:fixed.db?key=passphrase`

In the first place, you have to use an encryption enabled SQLite shell. Additionally, you will have to use URI parameters to specify encryption related parameters, like the passphrase, the cipher scheme etc (please consult the [SQLite3 Multiple Ciphers documentation](https://utelle.github.io/SQLite3MultipleCiphers/) for details).

For example, if you are not using the default cipher scheme, you will have to specify the `cipher` parameter:

`sqlite3mc_shell file:corrupted.db?cipher=aes128cbc&key=passphrase .recover | sqlite3mc_shell file:fixed.db?cipher=aes128cbc&key=passphrase`

For a cipher scheme that uses a HMAC you will have to disable the `hmac_check`:

`sqlite3mc_shell file:corrupted.db?hmac_check=0&key=passphrase .recover | sqlite3mc_shell file:fixed.db?key=passphrase`

Otherwise the process will stop on the first database page with an invalid HMAC.

You must be aware of the fact that it will be usually more difficult to recover a corrupted database that is encrypted. A single corrupted byte at the beginning of an encrypted database page will usually make the whole page content unusable. Therefore it is highly recommended to create database backups more frequently.

**Comment by Jun90925** [comment]
> 

Thank you!!
