### ISSUE TITLE
some bug 

### ISSUE THREAD

**Issue by playGitboy** [utelle/SQLite3MultipleCiphers#93]
When using the ".excel" option to open the query results with Excel by default, Chinese characters are displayed as garbled code.
Suggest using "UTF8-BOM" encoding for the generated csv file by default to solve the above bug.

Suggest adding the ".csv" option to export data to csv files directly.

**Comment by utelle** [comment]
> When using the ".excel" option to open the query results with Excel by default, Chinese characters are displayed as garbled code. Suggest using "UTF8-BOM" encoding for the generated csv file by default to solve the above bug.

Sorry, this is an issue of the _SQLite CLI_. The _SQLite library_ itself and the _SQLite CLI_ are developed and maintained by the [SQLite core developer team](https://www.sqlite.org/crew.html), not by me. The project **SQLite3 Multiple Ciphers** just adds database encryption options to the original SQLite library.

However, you may report this issue on the [official SQLite forum](https://www.sqlite.org/forum/).

> Suggest adding the ".csv" option to export data to csv files directly.

Again, this is nothing I can help with. Please ask for such an enhancement for the _SQLite CLI_ on the [SQLite forum](https://www.sqlite.org/forum/).

I'm closing this issue, because it is not related to the encryption extension provided by this project.
