### ISSUE TITLE
The project works for SQLite versions before the 3.32.0?

### ISSUE THREAD

**Issue by Zapotecatl** [utelle/SQLite3MultipleCiphers#94]
Hi, sorry, maybe it is a silly question, I saw in the wxSQLite3 documentation this:

"Since August 2020 a new implementation of an encryption extension, capable of supporting SQLite version 3.32.0 and later, is available as a separate project, SQLite3 Multiple Ciphers. Starting with the release of wxSQLite3 4.6.0 this new implementation is used."

I want to use SQLite3 Multiple Ciphers in my SQLite database version 3.31.1, can I use it?

**Comment by utelle** [comment]
> I saw in the wxSQLite3 documentation this:
> 
> "Since August 2020 a new implementation of an encryption extension, capable of supporting SQLite version 3.32.0 and later, is available as a separate project, SQLite3 Multiple Ciphers. Starting with the release of wxSQLite3 4.6.0 this new implementation is used."
> 
> I want to use SQLite3 Multiple Ciphers in my SQLite database version 3.31.1, can I use it?

Short answer: _**No**_. The first _SQLite_ version that was supported by this project was version _3.33.0_. The simplest way to use _SQLite version 3.31.1_ - if you can't update to a newer version for whatever reason - would be to stick with [wxSQLite3 4.5.1](https://github.com/utelle/wxsqlite3/releases/tag/v4.5.1).

Long answer: _**Maybe**_. The main obstacle will be the process to apply the required patches to the original SQLite amalgamation source code. It would be necessary to adjust at least the patch script `scripts\patchsqlite3.sh`. However, that won't be a trivial task (but doable, if you are ready to dedicate some time to analyze the patch script).

Actually, my recommendation would be to update your application to use the latest _wxSQLite3_ version. Since the _SQLite_ database files are compatible with those produced by older versions of _SQLite_, this should not impose any serious problems.

**Comment by Zapotecatl** [comment]
Hi @utelle , thank you for your quick answer and your recommendation.

Only for clarify if I understand you correctly.

My application currently use Linux ubuntu Ubuntu 20.04.4 LTS and SQLite 3.31.1.

Then I have two option:

1. I need update SQLite at least to 3.33.0. version and I can use the SQLite3 Multiple Ciphers.

2. I can keep with SQLite 3.31.1 and I can use wxSQLite3 4.5.1. (I understanding it is compatible with Linux)

That is correct?

and finally, thinking in the future, what do you think is the best option?

Thanks lot for take your time!

**Comment by Zapotecatl** [comment]
@utelle Thanks a lot for your help. My first approach will be use SQLite3 Multiple Ciphers and updated SQLite.
